# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pnorm5_ad <- function(x, mu, sigma, lower_tail, log_p) {
    .Call(`_RTMBconvenience_pnorm5_ad`, x, mu, sigma, lower_tail, log_p)
}

log_ipnorm_ad <- function(x, y, mu, sigma) {
    .Call(`_RTMBconvenience_log_ipnorm_ad`, x, y, mu, sigma)
}

pt_ad <- function(x, df, lower_tail, log_p) {
    .Call(`_RTMBconvenience_pt_ad`, x, df, lower_tail, log_p)
}

pde_scheme_ad <- function(x) {
    .Call(`_RTMBconvenience_pde_scheme_ad`, x)
}

logspace_add_ad <- function(x, y) {
    .Call(`_RTMBconvenience_logspace_add_ad`, x, y)
}

logspace_sum_ad <- function(x) {
    .Call(`_RTMBconvenience_logspace_sum_ad`, x)
}

logspace_sub_ad <- function(x, y) {
    .Call(`_RTMBconvenience_logspace_sub_ad`, x, y)
}

quantreg_ad <- function(x, tau) {
    .Call(`_RTMBconvenience_quantreg_ad`, x, tau)
}

login_log_besselI_ad <- function(logx, nu) {
    .Call(`_RTMBconvenience_login_log_besselI_ad`, logx, nu)
}

log_besselI_ad <- function(x, nu) {
    .Call(`_RTMBconvenience_log_besselI_ad`, x, nu)
}

log_MarcumQ_ad <- function(a, b, nu) {
    .Call(`_RTMBconvenience_log_MarcumQ_ad`, a, b, nu)
}

login_log_MarcumQ_ad <- function(loga, logb, nu) {
    .Call(`_RTMBconvenience_login_log_MarcumQ_ad`, loga, logb, nu)
}

log_Marcum1mQ_ad <- function(a, b, nu) {
    .Call(`_RTMBconvenience_log_Marcum1mQ_ad`, a, b, nu)
}

login_log_Marcum1mQ_ad <- function(loga, logb, nu) {
    .Call(`_RTMBconvenience_login_log_Marcum1mQ_ad`, loga, logb, nu)
}

logdrice_ad <- function(logx, lognu, logsigma) {
    .Call(`_RTMBconvenience_logdrice_ad`, logx, lognu, logsigma)
}

logprice_ad <- function(logx, lognu, logsigma, lower_tail) {
    .Call(`_RTMBconvenience_logprice_ad`, logx, lognu, logsigma, lower_tail)
}

